# Generated by Django 4.1.7 on 2023-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cryptoName', models.CharField(max_length=100)),
                ('Targetprice', models.IntegerField()),
            ],
        ),
    ]
