# Generated by Django 4.1.7 on 2023-04-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0005_exchange_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='token_app.exchange'),
        ),
    ]
